name: CI-triggered-by.direct-merge

on:
    push:
        branches: ['master', 'main', 'prerelease']
        paths-ignore: [
          README.md
        ]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    classify-change:
        name: Push
        permissions:
            contents: read
            pull-requests: read
        secrets: inherit
        with:
            event-name: ${{ github.event_name }}
            ref-name: ${{ github.ref_name }}
            head-sha: ${{ github.sha }}
            repository: ${{ github.repository }}
            commit-message: ${{ github.event.head_commit.message }}
        uses: ./.github/workflows/classify-change.yml

    code-checks:
        name: Linters
        needs: classify-change
        if: needs.classify-change.outputs.full-checks-required == 'true'
        uses: ./.github/workflows/code-checks.yml

    tests:
        name: Tests
        needs: [classify-change, code-checks]
        if: needs.classify-change.outputs.full-checks-required == 'true'
        uses: ./.github/workflows/tests.yml

    build:
        name: Build
        needs: [classify-change, code-checks, tests]
        if: needs.classify-change.outputs.full-checks-required == 'true'
        uses: ./.github/workflows/build.yml

    deploy:
        name: Release
        needs: [classify-change, build]
        if:
            always()
            && needs.classify-change.outputs.release-branch-push == 'true'
            && (
                needs.classify-change.outputs.merged-pr-push == 'true'
                || needs.build.result == 'success'
            )
        permissions:
            contents: write
            issues: write
            pull-requests: write
        secrets: inherit
        uses: ./.github/workflows/release.yml

    publish:
        name: Publish
        needs: deploy
        if:
            always()
            && needs.deploy.result == 'success'
            && needs.deploy.outputs.should-release == 'true'
        permissions:
            contents: read
            pages: write
            id-token: write
        uses: ./.github/workflows/publish.yml
