name: Validate

on:
    workflow_call:
    workflow_dispatch:

jobs:
    eslint:
        name: ESLint
        runs-on: ubuntu-latest
        steps:
            - name: Setup project
              uses: ./.github/actions/setup

            - name: Run ESLint 🚀
              run: bun run lint

    type-check:
        name: TS check
        runs-on: ubuntu-latest
        steps:
            - name: Setup project
              uses: ./.github/actions/setup

            - name: Run type checking 🚀
              run: bun run type-check
