name: Setup env
on:
    workflow_call:
    workflow_dispatch: #Allows manual run

jobs:
    setup_environment:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the source branch of the pull request
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref || github.ref }}

            - name: Display current branch
              run: git branch

            - name: Setup Bun 🛠️
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: 1.2.21

            - name: Cache dependencies 🛠️
              id: cache-deps
              uses: actions/cache@v4
              with:
                  path: ~/.bun/install/cache
                  key: bun-${{ runner.os }}-${{ hashFiles('**/bun.lock') }}
                  restore-keys: |
                      bun-${{ runner.os }}-

            - name: Install dependencies 🛠️
              run: bun install --frozen-lockfile
