name: Tests

on:
    workflow_call:
    workflow_dispatch:

concurrency:
    group: tests-${{ github.ref }}
    cancel-in-progress: true

jobs:
    unit:
        runs-on: ubuntu-latest

        steps:
          - name: Setup project
            uses: ./.github/actions/setup

          - name: Run unit and integration tests 🛠️
            run: bun run test

    e2e:
        runs-on: ubuntu-latest

        steps:
            - name: Setup project
              uses: ./.github/actions/setup

            - name: Install Playwright browsers 🛠️
              run: bunx playwright install --with-deps

            - name: Run end-to-end tests 🛠️
              run: bun run test:e2e